version: '3.5'

services:
  vector:
    container_name: llm-tool
    image: aitoolbox/llm-tool
    build: 
      context: ./service
    ports:
      - "12345:80"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
